### ISSUE TITLE
Dataset processing

### ISSUE THREAD

**Issue by adroit91** [MarkWuNLP/TACNTN#1]
Since the dataset you pointed to is in the form of pure text files, and you seem to be using a binary form of it, would you be adding the preprocessing part to convert "ubuntudata" into your "raw3.bin" image?

**Comment by MarkWuNLP** [comment]
I have a preprocess file named process_ubuntu.py .  You can take a look~

if you have read my paper, you know I need a topic index for the message and response receptively. If you just want to check whether the code can be run successfully, you can set topic and topic_r using an int (such 0).  Otherwise, you have to run a topic model and assign a topic number for message and response receptively.

For your convenient, I will upload my bin file to somewhere you can download this week, but it is a big file~

**Comment by adroit91** [comment]
Sure, thanks a lot! I will check out the file. Have read your paper though.

And, I understand about the bin file. Whenever it is available, it would be great!

**Comment by MarkWuNLP** [comment]
Well, the code is very dirty and has some hard code. If you have any problem, you can ask me for free.

**Comment by adroit91** [comment]
Sure, thanks! :)

**Comment by MarkWuNLP** [comment]
I uploaded my bin file at the following location
https://1drv.ms/u/s!AtcxwlQuQjw1jFEGdnZ5kMpJZT6S   training file
https://1drv.ms/u/s!AtcxwlQuQjw1jFLzkKDyhHLh-1pz   testing file

and I changedmy code a little bit. I think you can run my code directly.

**Comment by adroit91** [comment]
Thank you very much. Will try it out and let you know as well.

In case you think we can work together, please let me know. Would love to take this forward.
